<select name="state">
	<option value=" ">&#160;</option>
	<option value="AL" <%if Request("State") = "AL" then Response.Write( "selected" ) end if%>>AL</option>
	<option value="AK" <%if Request("State") = "AK" then Response.Write( "selected" ) end if%>>AK</option>
	<option value="AZ" <%if Request("State") = "AZ" then Response.Write( "selected" ) end if%>>AZ</option>
	<option value="AR" <%if Request("State") = "AR" then Response.Write( "selected" ) end if%>>AR</option>
	<option value="CA" <%if Request("State") = "CA" then Response.Write( "selected" ) end if%>>CA</option>
	<option value="CO" <%if Request("State") = "CO" then Response.Write( "selected" ) end if%>>CO</option>
	<option value="CT" <%if Request("State") = "CT" then Response.Write( "selected" ) end if%>>CT</option>
	<option value="DE" <%if Request("State") = "DE" then Response.Write( "selected" ) end if%>>DE</option>
	<option value="DC" <%if Request("State") = "DC" then Response.Write( "selected" ) end if%>>DC</option>
	<option value="FL" <%if Request("State") = "FL" then Response.Write( "selected" ) end if%>>FL</option>
	<option value="GA" <%if Request("State") = "GA" then Response.Write( "selected" ) end if%>>GA</option>
	<option value="HI" <%if Request("State") = "HI" then Response.Write( "selected" ) end if%>>HI</option>
	<option value="ID" <%if Request("State") = "ID" then Response.Write( "selected" ) end if%>>ID</option>
	<option value="IL" <%if Request("State") = "IL" then Response.Write( "selected" ) end if%>>IL</option>
	<option value="IN" <%if Request("State") = "IN" then Response.Write( "selected" ) end if%>>IN</option>
	<option value="IA" <%if Request("State") = "IA" then Response.Write( "selected" ) end if%>>IA</option>
	<option value="KS" <%if Request("State") = "KS" then Response.Write( "selected" ) end if%>>KS</option>
	<option value="KY" <%if Request("State") = "KY" then Response.Write( "selected" ) end if%>>KY</option>
	<option value="LA" <%if Request("State") = "LA" then Response.Write( "selected" ) end if%>>LA</option>
	<option value="ME" <%if Request("State") = "ME" then Response.Write( "selected" ) end if%>>ME</option>
	<option value="MD" <%if Request("State") = "MD" then Response.Write( "selected" ) end if%>>MD</option>
	<option value="MA" <%if Request("State") = "MA" then Response.Write( "selected" ) end if%>>MA</option>
	<option value="MI" <%if Request("State") = "MI" then Response.Write( "selected" ) end if%>>MI</option>
	<option value="MN" <%if Request("State") = "MN" then Response.Write( "selected" ) end if%>>MN</option>
	<option value="MS" <%if Request("State") = "MS" then Response.Write( "selected" ) end if%>>MS</option>
	<option value="MO" <%if Request("State") = "MO" then Response.Write( "selected" ) end if%>>MO</option>
	<option value="MT" <%if Request("State") = "MT" then Response.Write( "selected" ) end if%>>MT</option>
	<option value="NE" <%if Request("State") = "NE" then Response.Write( "selected" ) end if%>>NE</option>
	<option value="NV" <%if Request("State") = "NV" then Response.Write( "selected" ) end if%>>NV</option>
	<option value="NH" <%if Request("State") = "NH" then Response.Write( "selected" ) end if%>>NH</option>
	<option value="NJ" <%if Request("State") = "NJ" then Response.Write( "selected" ) end if%>>NJ</option>
	<option value="NM" <%if Request("State") = "NM" then Response.Write( "selected" ) end if%>>NM</option>
	<option value="NY" <%if Request("State") = "NY" then Response.Write( "selected" ) end if%>>NY</option>
	<option value="NC" <%if Request("State") = "NC" then Response.Write( "selected" ) end if%>>NC</option>
	<option value="ND" <%if Request("State") = "ND" then Response.Write( "selected" ) end if%>>ND</option>
	<option value="OH" <%if Request("State") = "OH" then Response.Write( "selected" ) end if%>>OH</option>
	<option value="OK" <%if Request("State") = "OK" then Response.Write( "selected" ) end if%>>OK</option>
	<option value="OR" <%if Request("State") = "OR" then Response.Write( "selected" ) end if%>>OR</option>
	<option value="PA" <%if Request("State") = "PA" then Response.Write( "selected" ) end if%>>PA</option>
	<option value="PR" <%if Request("State") = "PR" then Response.Write( "selected" ) end if%>>PR</option>
	<option value="RI" <%if Request("State") = "RI" then Response.Write( "selected" ) end if%>>RI</option>
	<option value="SC" <%if Request("State") = "SC" then Response.Write( "selected" ) end if%>>SC</option>
	<option value="SD" <%if Request("State") = "SD" then Response.Write( "selected" ) end if%>>SD</option>
	<option value="TN" <%if Request("State") = "TN" then Response.Write( "selected" ) end if%>>TN</option>
	<option value="TX" <%if Request("State") = "TX" then Response.Write( "selected" ) end if%>>TX</option>
	<option value="UT" <%if Request("State") = "UT" then Response.Write( "selected" ) end if%>>UT</option>
	<option value="VT" <%if Request("State") = "VT" then Response.Write( "selected" ) end if%>>VT</option>
	<option value="VA" <%if Request("State") = "VA" then Response.Write( "selected" ) end if%>>VA</option>
	<option value="WA" <%if Request("State") = "WA" then Response.Write( "selected" ) end if%>>WA</option>
	<option value="WV" <%if Request("State") = "WV" then Response.Write( "selected" ) end if%>>WV</option>
	<option value="WI" <%if Request("State") = "WI" then Response.Write( "selected" ) end if%>>WI</option>
	<option value="WY" <%if Request("State") = "WY" then Response.Write( "selected" ) end if%>>WY</option>
	<option value="">-----</option>
	<option value="AB" <%if Request("State") = "AB" then Response.Write( "selected" ) end if%>>AB</option>
	<option value="BC" <%if Request("State") = "BC" then Response.Write( "selected" ) end if%>>BC</option>
	<option value="MB" <%if Request("State") = "MB" then Response.Write( "selected" ) end if%>>MB</option>
	<option value="NB" <%if Request("State") = "NB" then Response.Write( "selected" ) end if%>>NB</option>
	<option value="NF" <%if Request("State") = "NF" then Response.Write( "selected" ) end if%>>NF</option>
	<option value="NT" <%if Request("State") = "NT" then Response.Write( "selected" ) end if%>>NT</option>
	<option value="NS" <%if Request("State") = "NS" then Response.Write( "selected" ) end if%>>NS</option>
	<option value="NU" <%if Request("State") = "NU" then Response.Write( "selected" ) end if%>>NU</option>
	<option value="ON" <%if Request("State") = "ON" then Response.Write( "selected" ) end if%>>ON</option>
	<option value="PE" <%if Request("State") = "PE" then Response.Write( "selected" ) end if%>>PE</option>
	<option value="QC" <%if Request("State") = "QC" then Response.Write( "selected" ) end if%>>QC</option>
	<option value="SK" <%if Request("State") = "SK" then Response.Write( "selected" ) end if%>>SK</option>
	<option value="YT" <%if Request("State") = "YT" then Response.Write( "selected" ) end if%>>YT</option>
</select>